### PR TITLE
Fingerprint functionality to admin

### PR DESCRIPTION
**Pull request by zyml**
This PR allows admins to view confessions filtered by fingerprint, and to view the number of featured / approved / pending / rejected confession counts beside the comments icon.

### CODE REVIEW

**Comment by yangshun** [comment]
Can't wait to use this 😁

**Comment by zhouyichen** [comment]
Ah, the mention-bot is quite cool.

**Comment by yangshun** [comment]
Sorry @zhouyichen  I shouldn't have added the bot to the whole organization. Have added it individually to nusmods and nusmods-api instead. Feel free to add it back to nuswhispers repo if you like: https://github.com/facebook/mention-bot

**Comment by zyml** [comment]
It's live. :)

**Pull request merged**
